[project]
name = "server"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.129.2",
    "paddlepaddle>=2.6.0",
    "paddleocr>=2.7.0",
    "chromadb>=0.4.0",
    "sentence-transformers>=2.2.0",
]
